apiVersion: v1
kind: Service
metadata:
  name: hello-server-service
spec:
  selector:
      app: hello-server # Service を利用したい Pod のラベルと一致させる
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # 利用するコンテナが解放している Port を指定する